"""
This type stub file was generated by cyright.
"""

from .xhptdc8_interface import *
from .crono_interface import *

def py_print_error(): # -> None:
    ...

def get_grouping(): # -> unsigned char:
    ...

def initialize_tdc(buffer_size: int): # -> int:
    ...

def get_default_configuration(): # -> unsigned char:
    ...

def start_capture(): # -> None:
    ...

def stop_capture(): # -> None:
    ...

def close_tdc(): # -> None:
    ...

def print_device_info(): # -> None:
    ...

def count_devices() -> int:
    """ Returns the number of boards present in the system that are supported by the current driver. """
    ...

def get_driver_revision() -> int:
    """ Returns the driver version, same format as static_info.driver_revision. 
    This function does not require a xHPTDC8_PCIe board to be present."""
    ...

def get_driver_revision_str() -> str:
    """ Returns the driver version, including SVN build revision as a string.
    This function does not require a xHPTDC8_PCIe board to be present."""
    ...

